# Generated by Django 4.2.4 on 2024-08-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='investigation_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='medication_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='treatment_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('insurance', 'Insurance')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
