# Generated by Django 4.2.4 on 2023-08-24 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_medicalhistory_options_remove_patient_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Treatment',
        ),
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='service',
            new_name='treatment',
        ),
    ]
