# Generated by Django 4.2.4 on 2024-08-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_medicalhistory_investigation_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='BPressure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='DOB',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
