# Generated by Django 4.2 on 2024-08-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_patient_dor_alter_patient_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='notes',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
