# Generated by Django 4.2.4 on 2023-08-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_patient_bpressure_patient_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='treatment',
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='treatment',
            field=models.ManyToManyField(to='patient.treatment'),
        ),
    ]
