# Generated by Django 4.2 on 2024-08-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_medicalhistory_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='permanent_dentition',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='temporary_dentition',
            field=models.JSONField(default=dict),
        ),
    ]
