# Generated by Django 4.2 on 2024-08-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_medicalhistory_permanent_dentition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='permanent_dentition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='temporary_dentition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
