# Generated by Django 4.2.4 on 2023-08-30 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_diagnosis_price_examination_price_investgation_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='price',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='price',
        ),
        migrations.RemoveField(
            model_name='reviewofsystem',
            name='price',
        ),
    ]
