# Generated by Django 4.2.4 on 2023-08-30 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_remove_diagnosis_price_remove_examination_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='amount',
        ),
    ]
